### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by BalconyJH** [yzyyz1387/nonebot_plugin_admin#1]
### 描述对应的功能内容：

希望增加关键词匹配快速匹配通过加入群聊

### 说出你的解决建议：

判断权限为superuser&group_admin&group_owner，写入json或sql，matcher捕获入群comment（验证信息）进行模糊匹配，成功同意请求，失败则返回相应理由。

### 描述你想实现的内容：

1. 权限判断仅限superuser&group_admin&group_owner
2. 加群请求无论结果均发送给该群聊指定admin或特定user（多群聊）
3. 匹配词进行模糊匹配，提供参数指定匹配词匹配数量
4. superuser私聊bot修改指定群聊匹配词

### 其他内容：

十分感谢此项目的建立与编写，对作者的付出表示尊敬，综上。

**Comment by yzyyz1387** [comment]
Got it, it's coming soon. ![](https://api.isoyu.com/uploads/ARU/GIF_S/3020.gif)

**Comment by yzyyz1387** [comment]
This demand has been basically solved, enjoy it now.  ![](https://api.isoyu.com/uploads/ARU/GIF_S/6140.gif)

**Comment by BalconyJH** [comment]
加群请求无论结果均发送给该群聊指定admin或特定user（多群聊），可选是否将结果返回superuser
