### ISSUE TITLE
[BUG] 插件运行过程中邀请机器人加入群聊报错

### ISSUE THREAD

**Issue by lakwsh** [yzyyz1387/nonebot_plugin_admin#10]
大概是开关未初始化之类吧

> 03-17 18:18:53 [INFO] nonebot | Matcher <Matcher from plugins.nonebot_plugin_admin.group_request, type=request, priority=1, temp=False> running complete
> 03-17 18:18:53 [ERROR] nonebot | Running matcher <Matcher from plugins.nonebot_plugin_admin.group_request, type=request, priority=1, temp=False> failed.
> Traceback (most recent call last):
>   File "D:\QQBot\NoneBot\bot.py", line 12, in <module>
>     nonebot.run()
>   File "D:\Python39\lib\site-packages\nonebot\__init__.py", line 258, in run
>     get_driver().run(*args, **kwargs)
>   File "D:\Python39\lib\site-packages\nonebot\drivers\fastapi.py", line 168, in run
>     uvicorn.run(
>   File "D:\Python39\lib\site-packages\uvicorn\main.py", line 463, in run
>     server.run()
>   File "D:\Python39\lib\site-packages\uvicorn\server.py", line 60, in run
>     return asyncio.run(self.serve(sockets=sockets))
>   File "D:\Python39\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "D:\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
>     self.run_forever()
>   File "D:\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
>     super().run_forever()
>   File "D:\Python39\lib\asyncio\base_events.py", line 596, in run_forever
>     self._run_once()
>   File "D:\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
>     handle._run()
>   File "D:\Python39\lib\asyncio\events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "D:\Python39\lib\site-packages\nonebot\message.py", line 153, in _check_matcher
>     await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
>   File "D:\Python39\lib\site-packages\nonebot\message.py", line 202, in _run_matcher
>     await matcher.run(bot, event, state, stack, dependency_cache)
>   File "D:\Python39\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
>     await self.simple_run(bot, event, state, stack, dependency_cache)
>   File "D:\Python39\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
>     await handler(
>   File "D:\Python39\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
>     return await self.call(**values)
>   File "D:\QQBot\NoneBot\plugins\nonebot_plugin_admin\group_request.py", line 163, in gr_
>     status = await check_func_status("requests", str(gid))
>   File "D:\QQBot\NoneBot\plugins\nonebot_plugin_admin\utils.py", line 373, in check_func_status
>     if funcs_status[gid][func_name]:
> KeyError: '群号'

**Comment by Dclef** [comment]
应该是 没有在config/开关.json里面去初始化开关的功能，导致没有找到群号，添加上就行了。
      "xxxxxxxxxx": {
        "admin": true,
        "requests": true,
        "wordcloud": true,
        "auto_ban": true,
        "img_check": true
    }

**Comment by yzyyz1387** [comment]
拉新群后gocq那边获取不到新群(缓存什么的)，要重启gocq才行

**Comment by yixue99** [comment]
`f not os.path.exists(limit_level):
        bot = nonebot.get_bot()
        logger.info("创建违禁词监控等级配置文件,分群设置,默认easy")
        g_list = (await bot.get_group_list())
        print(g_list)
        level_dict = {}
        for group in g_list:
            level_dict.update({str(group['group_id']): "easy"})
        with open(limit_level, "w", encoding='utf-8') as lwp:
            lwp.write(f'{json.dumps(level_dict)}')
            lwp.close()
    if not os.path.exists(switcher_path):
        bot = nonebot.get_bot()
        logger.info("创建开关配置文件,分群设置,默认开")
        g_list = (await bot.get_group_list())
        switcher_dict = {}
        for group in g_list:
            switcher_dict.update({str(group['group_id']): {"wordcloud": True, "auto_ban": True, "img_check": False}})
        with open(switcher_path, "w", encoding='utf-8') as swp:
            swp.write(f'{json.dumps(switcher_dict)}')
            swp.close()`

当违禁词监控等级配置文件及开关配置文件存在时，全关初始化，新加入的群没有写入对应的两个json文件，需要手动写入，初始化应该加上当两个文件存在时，读取文件并写入配置文件中没有的群，按默认的参数写入

**Comment by yzyyz1387** [comment]
> ![image](https://user-images.githubusercontent.com/50444999/169736183-f79d8817-45cf-457e-80bc-dabe2e0c00ad.png)
> 
> 当违禁词监控等级配置文件及开关配置文件存在时，群管初始化，新加入的群没有写入对应的两个json文件，需要手动写入，初始化应该加上当两个文件存在时，读取文件并写入配置文件中没有的群，按默认的参数写入

看不懂汉字咋的

**Comment by yixue99** [comment]
> > ![图像](https://user-images.githubusercontent.com/50444999/169736183-f79d8817-45cf-457e-80bc-dabe2e0c00ad.png)
> > 当违禁词监控等级配置文件及开关配置文件存在时，群管初始化，新加入的群没有写入对应的两个json文件，需要手动写入，初始化应该加上当两个文件存在时，读取文件并写入配置文件中没有的群，按默认的参数写入
> 
> 看不懂汉字咋的

打扰了~
