### ISSUE TITLE
消息拦截问题

### ISSUE THREAD

**Issue by Bearlele** [yzyyz1387/nonebot_plugin_admin#11]
block改成False或删除都无法解决消息被拦截问题 无法传给下一个插件

**Comment by yzyyz1387** [comment]
![](https://cdn.jsdelivr.net/gh/yzyyz1387/blogimages/no_pic_say_jb.jpg)

**Comment by Bearlele** [comment]
草 没有错误呀 就是消息nonebot_plugin_admin处理完了 然后就没有传给其他插件了 (

**Comment by yzyyz1387** [comment]
未接到其他用户出现此类问题，设计时肯定会考虑此问题，如果你坚信此问题存在，可通过修改本插件或者其他插件代码自行解决，此issues将close
