### ISSUE TITLE
希望能告诉一下根目录config文件夹内文件作用

### ISSUE THREAD

**Issue by CreeperAWA** [yzyyz1387/nonebot_plugin_admin#119]
希望能告诉一下根目录config文件夹内文件作用
同时我也想了解一下怎么设置权限（如：SUPERUSER、GROUP_ADMIN、GROUP_OWNER）

**Comment by yzyyz1387** [comment]
文件的作用可以从文件名看出来，用户一般不必直接操作。
`SUPERUSER` 是机器人超级用户（主人），在nonnebot的配置文件(.env开头的文件)中进行配置
`GROUP_ADMIN`是群管理员
`GROUP_OWNER`是群主
本插件定义了一个`DEPUTY_ADMIN`  对于基础的一些群管权限可以进行操作(踢禁改等等)，但对于管理员的任命与罢免无法进行操作
该权限可以通过**群主 \ 管理员 \ 机器人超级用户（主人）** 发送以下命令来进行设置
```
分管+ [user] ：user可用@或qq 添加分群管理员
分管- [user] ：删除分群管理员
```
例如
```
分管+ @某人
```

该`DEPUTY_ADMIN` 在某个群设置后，只在这个群内享有权限，同一个用户在A群被设置为`DEPUTY_ADMIN` ，但是其他群不具有由此权限（其他群没设置过的前提下）

**Comment by CreeperAWA** [comment]
我的.env文件所有东西都要自己手动加，默认是空的，我不清楚怎么加(

**Comment by yzyyz1387** [comment]
Nonebot作为一个**牛而逼之**的框架，这类问题你可以从他的文档找到 https://nonebot.dev/docs/tutorial/application#%E5%88%9B%E5%BB%BA%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by yzyyz1387** [comment]
项目根目录：
![image](https://github.com/yzyyz1387/nonebot_plugin_admin/assets/51691024/a61208c9-41b0-4bec-b922-118d7016eefa)

在`.env`中，配置`ENVIRONMENT=dev`
则nb回加载`.env.dev`中的配置，prod同理
我的部分配置供参考
![image](https://github.com/yzyyz1387/nonebot_plugin_admin/assets/51691024/8b310429-7d0a-4add-a3f8-d0f0405cb471)

**Comment by CreeperAWA** [comment]
我不太清楚我的Nonebot是不是有问题，我的只有`.env.prod`

**Comment by yzyyz1387** [comment]
这个是方便开发的，只有prod也无妨

**Comment by CreeperAWA** [comment]
我想把违禁词禁言时间固定，或者每个词都定一个禁言时间，该怎么办？

**Comment by CreeperAWA** [comment]
我再描述详细一点：就是我想把不同等级禁言时间固定，不再随机，我修改了`path.py`里最后几行的时间，只留下了一个固定时间，但运行后报错

**Comment by yzyyz1387** [comment]
Similar to #123
