### ISSUE TITLE
成功载入，但在使用的过程中出现error，貌似是字符编码问题

### ISSUE THREAD

**Issue by JinLiNianJi** [yzyyz1387/nonebot_plugin_admin#12]
请问这样要怎么解决
![IYF4UB ~AUW4(_KUA~TLA~D](https://user-images.githubusercontent.com/103938846/164246465-56bd0749-0a9d-4af5-b6f0-7fff856a5b2a.png)
![DEO{%)XPYNOE$KOE8RM~}{6](https://user-images.githubusercontent.com/103938846/164246515-fdb48542-0dfd-43e5-9234-13f918c69872.png)

问开关状态会回答这样一张图，问其他的没有反应并且报上图的错
![{1Z47D(5H%2CJ 0HU$DR25O](https://user-images.githubusercontent.com/103938846/164246735-00a1b3eb-7eb4-4bec-9e0a-00f6b27f32ff.PNG)

**Comment by lakwsh** [comment]
用pip装的吧，这个问题我已经修过了，但pip上没更新。。。😓

**Comment by JinLiNianJi** [comment]
下载压缩包，直接引入插件后依然报错
![~~W@OGI`8GPFVIOVXOHGG}Q](https://user-images.githubusercontent.com/103938846/164476522-a46edb06-58f7-4884-81c5-6f513ead5217.png)
![AK4Z(N 2}IQZV@I1Q1HNZIF](https://user-images.githubusercontent.com/103938846/164476558-a48b0dea-60c1-44a3-82be-963d891d653c.png)
![YVG%B9@C1F E{ 3BS Q$783](https://user-images.githubusercontent.com/103938846/164476646-63699287-9c46-4089-985c-bed89a45b050.png)
问开关状态虽然报错，但是会回复正常图片，输入其他指令（如：禁 @xxx）没有反应会报错
![$AV%GPQG`$( 40 Z08E(EWC](https://user-images.githubusercontent.com/103938846/164477508-f0f90196-fa88-451d-883d-a9384b92f044.png)
![JGVDY2X`YTFJ`G_X$WJ@N6V](https://user-images.githubusercontent.com/103938846/164477556-6d187776-5dee-4868-9bc8-ebb7c31db7e7.png)

**Comment by lakwsh** [comment]
嗯，你把旧的配置文件删掉试试，即删掉config文件夹

**Comment by JinLiNianJi** [comment]
删掉config文件夹中的相关部分以后可以正常运行了，感谢！

**Comment by JinLiNianJi** [comment]
等等，我删掉以后重启可以用了，但第二次启动又不可以用了……

**Comment by lakwsh** [comment]
整个config删掉呢？（或者你手动把文件编码都调到utf8也行）
另外麻烦贴一下报错

**Comment by JinLiNianJi** [comment]
整个config删掉以后，把zip解压放进去重装了一遍
第一次运行，报错是这样的：
![W}J (91O~Q3SS8LYK0X)@3](https://user-images.githubusercontent.com/103938846/164781612-76ffa64b-799e-4724-9f06-62236cd083e9.png)
![)(9K7(~$IXXCURRD2}V58QI](https://user-images.githubusercontent.com/103938846/164781649-df0f2b81-8e8b-48d3-98e1-106a77251135.png)
![9(HT4CM`F9M6NXZY2_%UR@8](https://user-images.githubusercontent.com/103938846/164781670-0f0f9c52-7dab-418c-b8ac-d8f64e3c09f3.png)
![KMAMG551K$P 1`5ORQI37}S](https://user-images.githubusercontent.com/103938846/164781695-e2c076e1-7ad6-457f-95bf-130da3ae8409.png)
![D~TD{U_7~ }_}_XLU QG634](https://user-images.githubusercontent.com/103938846/164781719-00eb835b-9d43-419f-a773-dbb76a8bcf26.png)
![BJZR ~( CZ(S4HT4XI9B(7L](https://user-images.githubusercontent.com/103938846/164781738-5d00acb8-8b67-4da9-9b76-8f9f3b23d895.png)
![XGV `O2(M)U7Z$48UN{TZME](https://user-images.githubusercontent.com/103938846/164781768-099de788-c895-4ad9-9181-e8cc7e1e1084.png)

第二次运行，载入的时候没有报错，但是在使用功能的时候报错了：
![7I(~ 8S` JNRPXE1O~F VIN](https://user-images.githubusercontent.com/103938846/164780229-3c1c9baa-3a10-4218-baf1-8219ae4fe611.png)

![98JTGRE~L8`EAW(MSRVK)8M](https://user-images.githubusercontent.com/103938846/164780121-6c374079-1a5a-4137-8b75-2fb6ef1cb3cd.png)

**Comment by lakwsh** [comment]
你这个是pip装的旧版本没卸载，导致加载插件的时候冲突了，你卸载了应该就好了
