### ISSUE TITLE
禁言功能存在 bug，使用`禁 @somebody`时无法工作

### ISSUE THREAD

**Issue by tom-snow** [yzyyz1387/nonebot_plugin_admin#15]
问题代码：
https://github.com/yzyyz1387/nonebot_plugin_admin/blob/68452c114c0c52c107e6e7e3dff6ddecea8f8d5d/nonebot_plugin_admin/__init__.py#L41

应改为：
```
if len(msg.split()) > len(sb)+1:
```

另外建议词云功能也像违禁词一样使用资源配置文件，并且考虑再创建一个 "custom" 文件来存储用户自定义的违禁词/词云忽略词，而且可以加个指令清除当前群的词云存储文件

**Comment by yzyyz1387** [comment]
问题一，代码没问题
问题二，日后考虑

**Comment by yzyyz1387** [comment]
问题一示例
![image](https://user-images.githubusercontent.com/51691024/170878433-fe59360a-93b2-4608-9461-b6671a840bd2.png)

**Comment by yzyyz1387** [comment]
+1是a16的写法
![image](https://user-images.githubusercontent.com/51691024/170878620-e82d8769-8936-4a42-b646-6db14b14b6bb.png)

**Comment by yzyyz1387** [comment]
你加空格了是吧，禁打完直接@不是方便点吗，后期再看看，把消息的空格处理了啥的![](https://api.isoyu.com/uploads/ARU/GIF_S/0460.gif)

**Comment by yzyyz1387** [comment]
确实，要不你pr一下，最近很忙

**Comment by yzyyz1387** [comment]
其实也不影响使用，所以没发现😂

**Comment by yzyyz1387** [comment]
> 问题代码：
> 
> https://github.com/yzyyz1387/nonebot_plugin_admin/blob/68452c114c0c52c107e6e7e3dff6ddecea8f8d5d/nonebot_plugin_admin/__init__.py#L41
> 
> 应改为：
> 
> ```
> if len(msg.split()) > len(sb)+1:
> ```
> 
> 另外建议词云功能也像违禁词一样使用资源配置文件，并且考虑再创建一个 "custom" 文件来存储用户自定义的违禁词/词云忽略词，而且可以加个指令清除当前群的词云存储文件

[TODO](https://github.com/yzyyz1387/nonebot_plugin_admin#todo)
