### ISSUE TITLE
功能建议：对引用的消息进行撤回

### ISSUE THREAD

**Issue by ATKghost** [yzyyz1387/nonebot_plugin_admin#19]
建议增加 /撤回 指令，对想要撤回的消息进行回复并使用 /撤回 指令，

用法示例：
```
[回复引用的消息]
/撤回

```
通过[CQ:reply,id=xxxxxx]中的id对引用消息进行撤回。

更进一步的功能：对撤回的内容进行保存，以保留证据。或发截图抄送管理？

**Comment by yzyyz1387** [comment]
见 https://github.com/yzyyz1387/nonebot_plugin_admin/pull/20 由@tom-snow 完成
使用仓库最新代码可抢先体验 ！![](https://api.isoyu.com/uploads/ARU/GIF_S/4301.gif)
