### ISSUE TITLE
群词云报错

### ISSUE THREAD

**Issue by liuzj288** [yzyyz1387/nonebot_plugin_admin#21]
![image](https://user-images.githubusercontent.com/13833404/177020276-0f2c2e55-a7ee-45f5-99c5-6737ad20fc48.png)

**Comment by yzyyz1387** [comment]
> ![image](https://user-images.githubusercontent.com/13833404/177020276-0f2c2e55-a7ee-45f5-99c5-6737ad20fc48.png)
> 

此问题已经修复过，不知道你使用的哪个版本呢，建议尝试
 - 拉仓库最新版使用
 - 或者使用 `pip install --upgrade nonebot-plugin-admin` 命令来更新

**Comment by liuzj288** [comment]
就是今天拉的镜像，难道是因为用的nb4？

**Comment by yzyyz1387** [comment]
> 就是今天拉的镜像，难道是因为用的nb4？

不是nb的问题，还有你这明显不是最新的，https://github.com/yzyyz1387/nonebot_plugin_admin/blob/main/nonebot_plugin_admin/word_analyze.py#L102
102行这都不一样
