### ISSUE TITLE
ModuleNotFoundError: No module named 'nonebot.adapters.onebot.v11.exception'

### ISSUE THREAD

**Issue by cuijiahuawx** [yzyyz1387/nonebot_plugin_admin#23]
## 命令行报错如下：  

```
File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot_plugin_admin/__init__.py", line 11, in <module>
    from nonebot.adapters.onebot.v11.exception import ActionFailed
ModuleNotFoundError: No module named 'nonebot.adapters.onebot.v11.exception'
```

**Comment by yzyyz1387** [comment]
> ## 命令行报错如下：  
> 
> ```
> File "/home/ubuntu/.local/lib/python3.10/site-packages/nonebot_plugin_admin/__init__.py", line 11, in <module>
>     from nonebot.adapters.onebot.v11.exception import ActionFailed
> ModuleNotFoundError: No module named 'nonebot.adapters.onebot.v11.exception'
> ```

#22
