### ISSUE TITLE
更改头衔错误 所有指令不在开头加/都用不了

### ISSUE THREAD

**Issue by Kiana1314** [yzyyz1387/nonebot_plugin_admin#24]
![M}5ML9BTDYC6D}ROC C~2~V](https://user-images.githubusercontent.com/107671434/178137659-8abcd575-36fe-4a3a-beb3-ecec5ce4712d.jpg)
![IWPB3XB(U0K`2N{74PH89KN](https://user-images.githubusercontent.com/107671434/178137663-38d1aa00-bab1-4019-811a-49b653389e71.png)

**Comment by yzyyz1387** [comment]
命令起始字符只与你nb的配置有关，与本插件无关，请自己排查
