### ISSUE TITLE
功能开关失效，通过指令关闭功能后仍可执行

### ISSUE THREAD

**Issue by just1greed** [yzyyz1387/nonebot_plugin_admin#26]
使用过程中发现关闭诸如违禁词、加群审批等功能后，该项功能仍正常运行，检查源码发现仅在__init__中导入switcher且判断status，其他功能(如违禁词)仅导入check_func_status函数而未使用，即无论开关状态如何，该功能均可运行
![1](https://user-images.githubusercontent.com/94421176/179358384-ad19a5da-adf8-479f-a1c0-309c6592cd81.png)
![image](https://user-images.githubusercontent.com/94421176/179358535-fb23abaf-4d3b-46ce-8eb1-a1d357123baf.png)

**Comment by yzyyz1387** [comment]
说得好，不过那个函数没啥用，因为开关现在是hook实现

**Comment by yzyyz1387** [comment]
![Screenshot_2022-07-16-22-23-21-65_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/51691024/179358854-8601b3a7-94d8-429a-9de8-0f4df04af54e.jpg)

诺，自己排查吧，我继续肝毕设

**Comment by just1greed** [comment]
果然是以我没想到的方式实现了吗，您！

**Comment by just1greed** [comment]
再不用pip下崽了🤡
