### ISSUE TITLE
新手安装，遇到了亿点问题awa（高血压提醒）

### ISSUE THREAD

**Issue by Cintser** [yzyyz1387/nonebot_plugin_admin#27]
请问本插件是否支持绪山真寻bot（Nonebot2）？
请问pip应该如何安装？图一为尝试在机器人本体中安装，图二为尝试在nb插件中安装
![QQ截图20220722145619](https://user-images.githubusercontent.com/98868806/180381984-8a86cb65-7fbc-4173-8bfc-a78c3061faac.jpg)
![QQ截图20220722150537](https://user-images.githubusercontent.com/98868806/180383218-f8b1f09f-dce5-4b50-b8f3-3e25abd1f2b7.jpg)
导入时是否编写bot本体的bot.py文件？如果是，请问该编写在第几行？
![image](https://user-images.githubusercontent.com/98868806/180384277-2f04abeb-547a-4784-b028-0857a146a507.png)
![image](https://user-images.githubusercontent.com/98868806/180384359-3649d56b-a424-443a-a1c5-d0d4923a272e.png)

**Comment by lakwsh** [comment]
血压up↑↑
你这个是网络问题，麻烦挂梯子安装
