### ISSUE TITLE
消息记录发生错误

### ISSUE THREAD

**Issue by liuzj288** [yzyyz1387/nonebot_plugin_admin#29]
![image](https://user-images.githubusercontent.com/13833404/181146202-da892670-7f99-4723-b762-20c65e71e9a5.png)

**Comment by yzyyz1387** [comment]
> ![image](https://user-images.githubusercontent.com/13833404/181146202-da892670-7f99-4723-b762-20c65e71e9a5.png)
> 

被捕捉了就不是bug😂
这个问题是个小bug，不知道哪儿有问题，今年没时间，你可以自己修一下再pr /滑稽

**Comment by liuzj288** [comment]
> > ![image](https://user-images.githubusercontent.com/13833404/181146202-da892670-7f99-4723-b762-20c65e71e9a5.png)
> 
> 被捕捉了就不是bug😂 这个问题是个小bug，不知道哪儿有问题，今年没时间，你可以自己修一下再pr /滑稽

还有这个记录问题
![image](https://user-images.githubusercontent.com/13833404/181149835-e3dd93b6-d4fd-44dc-a361-e546d196d707.png)

**Comment by yzyyz1387** [comment]
> ![image](https://user-images.githubusercontent.com/76118866/183827143-ecd284d2-3365-4b77-9bc2-9e0fa55ce7a0.png)
> 这个py好像真的有点大毛病了

插件问题，最近没时间修啊/哭

**Comment by yzyyz1387** [comment]
> 没事，用户粘性还是在的
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人: ***@***.***&gt;; 
> 发送时间: 2022年8月10日(星期三) 下午3:50
> 收件人: ***@***.***&gt;; 
> 抄送: ***@***.***&gt;; ***@***.***&gt;; 
> 主题: Re: [yzyyz1387/nonebot_plugin_admin] 消息记录发生错误 (Issue #29)
> 
> 
> 
> 
> 
>   
> 
>  这个py好像真的有点大毛病了
>   
> 插件问题，最近没时间修啊/哭
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

最近看看吧，这政治我是一句也看不下去了😔

**Comment by yzyyz1387** [comment]
> 加油加油
> 我clone下来研究研究

这玩意准备去掉了，因为go-cq已经提存了数据库，可以换成连接数据库的😂

**Comment by yzyyz1387** [comment]
> ![image](https://user-images.githubusercontent.com/76118866/183827143-ecd284d2-3365-4b77-9bc2-9e0fa55ce7a0.png) 这个py好像真的有点大毛病了

咋复现，我没遇到过

**Comment by yzyyz1387** [comment]
> ![image](https://user-images.githubusercontent.com/13833404/181146202-da892670-7f99-4723-b762-20c65e71e9a5.png)

这功能已经删掉了，因为之前写这个是为后续功能做准备，但时比较忙没写新功能，所以也没用上，后续有用会再完善

**Comment by yzyyz1387** [comment]
> > > ![image](https://user-images.githubusercontent.com/76118866/183827143-ecd284d2-3365-4b77-9bc2-9e0fa55ce7a0.png) 这个py好像真的有点大毛病了
> > 
> > 
> > 咋复现，我没遇到过
> 
> 之前我是正常pip安装的，我也不是很清楚，检查py文件好像也没问题

![](https://api.isoyu.com/uploads/ARU/GIF_S/0400.gif)

**Comment by yzyyz1387** [comment]
> > > ![image](https://user-images.githubusercontent.com/13833404/181146202-da892670-7f99-4723-b762-20c65e71e9a5.png)
> > 
> > 
> > 这功能已经删掉了，因为之前写这个是为后续功能做准备，但时比较忙没写新功能，所以也没用上，后续有用会再完善
> 
> 挺巧我也删掉了（

hhhhh
