### ISSUE TITLE
功能建议📋

### ISSUE THREAD

**Issue by BalconyJH** [yzyyz1387/nonebot_plugin_admin#3]
描述对应的功能内容：
- 希望增加关键词匹配自动禁言，关键词由群主/群管理员/超级用户添加分群/全局关键词
- 希望增加检测用户发出图片特征，控制非法图片的存留时间，接入第三方鉴黄api，进行二维码检测，通过识别后进行撤回并做出惩罚，惩罚依据时间戳或次数加以区分
- 希望增加对bot的恶意度检测，艾特bot进行辱骂或其余过激行为接入第二条所构建的惩罚系统

说出你的解决建议：
关键词模糊匹配，图片检测可以接入腾讯过其它第三方开放平台，惩罚系统区分为警告/禁言/bot拉黑/踢出群聊等更为非人性化措施，恶意度仅对艾特bot或者私聊做出判断，连续多次高强度触发bot亦应提升相应恶意度，已避免刷屏行为，图片撤回可选结果发送群主/群管理

其他内容：
十分感谢此项目的建立与编写，对作者的付出表示尊敬，综上。

**Comment by yzyyz1387** [comment]
**got it, it's coming sooooooooooooooooooooooooooooon**![](http://ww1.sinaimg.cn/bmiddle/814268e3gw1f1ad7zn7khg201f019742.gif)

**Comment by BalconyJH** [comment]
oooooooooooooooook🥰🥰
