### ISSUE TITLE
群词云在一个群能用在其他群没反应

### ISSUE THREAD

**Issue by liuzj288** [yzyyz1387/nonebot_plugin_admin#30]
其他群这之后就没反应了
![image](https://user-images.githubusercontent.com/13833404/181151651-79289034-c6e7-4ed8-8d2f-f43dd545bfd8.png)

能用的群可以正常调用wordcloud
![image](https://user-images.githubusercontent.com/13833404/181151875-705c34b9-8150-4b38-9cfa-91b3ffbeea33.png)

**Comment by yzyyz1387** [comment]
。。。。

**Comment by yzyyz1387** [comment]
这个貌似也没报错，我去看了下代码，应该是没有发送`记录本群`,这部分在代码中没做处理，会直接跳过

**Comment by yzyyz1387** [comment]
[commit: ac21651](https://github.com/yzyyz1387/nonebot_plugin_admin/commit/ac2165159ceb6afea4bdb666e1f1b14bd9fc7925#diff-4a07a544a1eab3044f85d2919da9f4bda5ddbe55ef59be497f60dc4e62d5067d)
