### ISSUE TITLE
关于图片检测

### ISSUE THREAD

**Issue by ID114514** [yzyyz1387/nonebot_plugin_admin#34]
目前是仅支持检测拦截色图吗，我看腾讯云那边有拦截政治性感方面的，但bot这边没有对应禁言撤回操作，
如果是仅支持拦截色图的话，希望增加拦截政治 性感 违法 暴恐 相关的，
还有就是能否自定义禁言等级，触发关键词默认为1级起步禁言，但触发色图 敏感方面的直接默认3级起步禁言

**Comment by yzyyz1387** [comment]
没有必要，需要的话自己改

**Comment by yzyyz1387** [comment]
https://github.com/yzyyz1387/nonebot_plugin_admin/blob/main/nonebot_plugin_admin/img_check.py#L33
在这里判断就行

**Comment by ID114514** [comment]
> https://github.com/yzyyz1387/nonebot_plugin_admin/blob/main/nonebot_plugin_admin/img_check.py#L33 在这里判断就行

了解了，感谢解答
