### ISSUE TITLE
严格违禁词报错

### ISSUE THREAD

**Issue by SEVEN-6174** [yzyyz1387/nonebot_plugin_admin#38]
![image](https://user-images.githubusercontent.com/107546075/186068010-63db822c-5632-483f-86ae-b2d792292ef5.png)
开启严格违禁词后报错
插件加载成功
但是每一条消息都有这个问题

**Comment by yzyyz1387** [comment]
这报错截全了吗，感觉下面还有,(没有当我没说)
看起来是正则的问题，正则部分不是我写的，如果你使用简单违禁词没有问题的话，建议使用之，因为严格违禁词实在鸡肋
对于违禁词你可以针对不同群在群内使用：
```
添加自定义违禁词 xxx xxx
删除自定义违禁词 xxx xxx
查看自定义违禁词
```
（违禁词以空格分隔）

此外，如果你是在商店下载的本插件，那么它或许不是最新的，你可以在github拉取开发版本（或许有不可预测的bug）

很高兴你能使用本插件，本人技术欠佳，日后将不断完善，

**Comment by SEVEN-6174** [comment]
> 这报错截全了吗，感觉下面还有,(没有当我没说) 看起来是正则的问题，正则部分不是我写的，如果你使用简单违禁词没有问题的话，建议使用之，因为严格违禁词实在鸡肋 对于违禁词你可以针对不同群在群内使用：
> 
> ```
> 添加自定义违禁词 xxx xxx
> 删除自定义违禁词 xxx xxx
> 查看自定义违禁词
> ```
> 
> （违禁词以空格分隔）
> 
> 此外，如果你是在商店下载的本插件，那么它或许不是最新的，你可以在github拉取开发版本（或许有不可预测的bug）
> 
> 很高兴你能使用本插件，本人技术欠佳，日后将不断完善，

全了
从github下的
那我还是用自定义把

**Comment by yzyyz1387** [comment]
建议这些错误和违禁词文件所使用的的jsdelivr在国内的问题，计划去掉自动更新违禁词，改为由用户自定义全局违禁词，插件只提供违禁词交易，你可以关注本插件后续更新
