### ISSUE TITLE
【BUG反馈】auto_ban.py

### ISSUE THREAD

**Issue by HuYihe2008** [yzyyz1387/nonebot_plugin_admin#42]
最新整改更新后出现违禁词bug
![image](https://user-images.githubusercontent.com/76118866/186555548-4fa18999-ae2e-440c-af08-08e8705a4c94.png)
可能为逻辑bug
![image](https://user-images.githubusercontent.com/76118866/186555574-84c5c10e-d61e-423c-a47b-0e35d016515d.png)

**Comment by yzyyz1387** [comment]
这功能已经删掉了

**Comment by yzyyz1387** [comment]
> 那为啥还会出现回应处理😅

😅
