### ISSUE TITLE
新人/请问pip该在哪安装？

### ISSUE THREAD

**Issue by Cintser** [yzyyz1387/nonebot_plugin_admin#45]
阿巴阿巴
![image](https://user-images.githubusercontent.com/98868806/187111428-3cdbca9a-e253-4a48-a41b-e7d1dfd179d3.png)

**Comment by lakwsh** [comment]
操作没问题，这属于网络问题
解决方法：肉体翻墙／全局代理／通过-i参数指定国内pip源
