### ISSUE TITLE
不太明白如何添加自定义违禁词

### ISSUE THREAD

**Issue by mogudunji** [yzyyz1387/nonebot_plugin_admin#46]
不太明白如何添加自定义违禁词

**Comment by lakwsh** [comment]
可以在群里发送“添加违禁词 xxx”，“查看违禁词”，“删除违禁词 xxx”来进行最简单的违禁词管理
目前的话没有想好怎么细化指令操作违禁词
建议是编辑违禁词.txt手动管理违禁词，例子的话：
  - 加(群|君\S?羊|羣)\S*\d{6,}		$撤回$禁言$仅限123456789,987654321
  - 狗群主				$禁言$排除987654321
可以这样理解，第一个规则匹配“加群123456”、“加群888888888”、“加君  羊12345678”等等，执行的操作是撤回＋禁言，生效群聊仅987654321和123456789两个
第二个规则只执行禁言操作，生效群聊为排除987654321以外的所有群聊
不对违禁词操作（右边那些）做定义的话，默认禁言＋撤回，所有群生效

**Comment by mogudunji** [comment]
> 可以在群里发送“添加违禁词 xxx”，“查看违禁词”，“删除违禁词 xxx”来进行最简单的违禁词管理 目前的话没有想好怎么细化指令操作违禁词 建议是编辑违禁词.txt手动管理违禁词，例子的话：
> 
> * 加(群|君\S?羊|羣)\S*\d{6,}		撤回撤回禁言$仅限123456789,987654321
> * 狗群主				禁言禁言排除987654321
> 
> 可以这样理解，第一个规则匹配“加群123456”、“加群888888888”、“加君 羊12345678”等等，执行的操作是撤回＋禁言，生效群聊仅987654321和123456789两个 第二个规则只执行禁言操作，生效群聊为排除987654321以外的所有群聊 不对违禁词操作（右边那些）做定义的话，默认禁言＋撤回，所有群生效

请问能设置禁言时间吗

**Comment by lakwsh** [comment]
> > 可以在群里发送“添加违禁词 xxx”，“查看违禁词”，“删除违禁词 xxx”来进行最简单的违禁词管理 目前的话没有想好怎么细化指令操作违禁词 建议是编辑违禁词.txt手动管理违禁词，例子的话：
> > 
> > * 加(群|君\S?羊|羣)\S*\d{6,}		撤回撤回禁言$仅限123456789,987654321
> > * 狗群主				禁言禁言排除987654321
> > 
> > 可以这样理解，第一个规则匹配“加群123456”、“加群888888888”、“加君 羊12345678”等等，执行的操作是撤回＋禁言，生效群聊仅987654321和123456789两个 第二个规则只执行禁言操作，生效群聊为排除987654321以外的所有群聊 不对违禁词操作（右边那些）做定义的话，默认禁言＋撤回，所有群生效
> 
> 请问能设置禁言时间吗

目前不支持设置禁言时长（以后应该会考虑）
