### ISSUE TITLE
不知道如何打开违禁词撤回，而且貌似也没有默认打开

### ISSUE THREAD

**Issue by zichuan0923** [yzyyz1387/nonebot_plugin_admin#47]
如题，大佬在文档里写的禁言和撤回都默认打开了。但似乎只有禁言是默认打开的。而且我也没有找到打开撤回的地方（可能是我眼瞎），希望大佬能在文档里加入QAQ

**Comment by lakwsh** [comment]
![image](https://user-images.githubusercontent.com/13025769/188886846-ebb2a289-ac80-4e72-a225-0151849bf911.png)
没有问题啊

**Comment by zichuan0923** [comment]
那大佬可以圈一下修改违禁词撤回在哪里吗，我是真找不到，麻烦你了QAQ

**Comment by lakwsh** [comment]
违禁词文件在**NoneBot\config\违禁词.txt**文件内
具体参考#46

**Comment by zichuan0923** [comment]
![捕获](https://user-images.githubusercontent.com/107084789/188917945-935e1c01-abbf-4f60-a919-3552e785dd61.PNG)
![捕获1](https://user-images.githubusercontent.com/107084789/188917955-765bca3a-28b4-4a8e-bf86-b99e44ca199e.PNG)
如截图所示，触发违禁词后，只进行了禁言操作，没有进行撤回，我并没有修改过有关撤回的配置文件QAQ

**Comment by zichuan0923** [comment]
![捕获](https://user-images.githubusercontent.com/107084789/188918560-3255056a-5625-44ee-907b-42275ef7caca.PNG)
![捕获1](https://user-images.githubusercontent.com/107084789/188918574-980ac413-1e78-43af-b323-c89428c457a7.PNG)
如截图所示，我并没有修改过有关撤回的配置文件，但是只有禁言操作，我纯纯萌新一个，参考的#46我还是不太懂，大佬可以展示一个修改好的手动管理撤回的例子吗，谢谢QAQ

**Comment by lakwsh** [comment]
> ![捕获](https://user-images.githubusercontent.com/107084789/188918560-3255056a-5625-44ee-907b-42275ef7caca.PNG) ![捕获1](https://user-images.githubusercontent.com/107084789/188918574-980ac413-1e78-43af-b323-c89428c457a7.PNG) 如截图所示，我并没有修改过有关撤回的配置文件，但是只有禁言操作，我纯纯萌新一个，参考的#46我还是不太懂，大佬可以展示一个修改好的手动管理撤回的例子吗，谢谢QAQ

你这个，该不会是用的pip版吧
![JSYTP{ X$W SQL5MPZQMCKQ](https://user-images.githubusercontent.com/13025769/189114460-c2039d7f-3676-4774-aa39-304d544712f7.png)
![JSYTP{ X$W SQL5MPZQMCKQ](https://user-images.githubusercontent.com/13025769/189114461-812c710e-4071-4052-afba-93abd0c4115b.png)

**Comment by lakwsh** [comment]
pip版可能是没有撤回功能（我也不知道现在pip是哪个版本了），需要的话建议直接下载github版
