### ISSUE TITLE
[BUG]群词云报错

### ISSUE THREAD

**Issue by zuixiaoxiao** [yzyyz1387/nonebot_plugin_admin#51]
**描述 bug**
救命啊，插件出现了群词云报错问题

**如何复现**
1. 我通过nb方式安装并导入了插件
2. 在 正常 时候 正常运行 情况下，出现了 群云词报错 问题

**报错截图 （python的报错请截最下面）**
这里放截图，可使用任何截图工具截图，然后在这里按下 ** Ctrl + V **
![image](https://user-images.githubusercontent.com/108536651/194709365-6e146001-496e-41d1-8814-24476886c288.png)

**环境**
 - 操作系统 win10
 - Python 版本 3.9.13
 - Nonebot2 版本号 不知道
 - 在那里下载的本插件 nonebot商店
  - pypi (商店安装 或者 pip 安装（本质一样）)
  - github ( 说明分支 )

**其他内容**
...

**Comment by yzyyz1387** [comment]
是否自己打开过记录文件之类的，请删除config/words试试

**Comment by yzyyz1387** [comment]
请从仓库拉最新版

**Comment by zuixiaoxiao** [comment]
> 请从仓库拉最新版

这个是因为没有安装wordcloud依赖的问题吗
![image](https://user-images.githubusercontent.com/108536651/200999800-a43682a6-95c4-43d5-8a2c-94c193a35e65.png)
![image](https://user-images.githubusercontent.com/108536651/200999843-5bbd721d-9ee8-4c93-ba9a-4546b33675bf.png)

**Comment by yzyyz1387** [comment]
试一下图片里提示的 
```
pip install imageio
```

**Comment by zuixiaoxiao** [comment]
> 试一下图片里提示的
> 
> ```
> pip install imageio
> ```

一样

**Comment by yzyyz1387** [comment]
报错一样吗，图呢，你拉仓库的装依赖了吗

**Comment by zuixiaoxiao** [comment]
> 报错一样吗，图呢，你拉仓库的装依赖了吗

一样，
![image](https://user-images.githubusercontent.com/108536651/201001437-940bb22f-613e-4d20-a743-1d84b4cc0f39.png)
群词云那个依赖跟我这个机器人的依赖好像冲突会，装了那个依赖机器人就没法启动了

**Comment by yzyyz1387** [comment]
如果依赖全装还不能用，请看一下 `机器人文件夹\config\wordcloud_bg`  下的图片是否正常，如果不正常（大小0k，显示图片损坏，那就是由于cdn的问题导致图片在下载时失败，目前没有这方面的错误处理），如果正常，那我就不知道了

**Comment by yzyyz1387** [comment]
nb商店还有词云插件来着，可以试试 https://github.com/he0119/nonebot-plugin-wordcloud

**Comment by zuixiaoxiao** [comment]
> 如果依赖全装还不能用，请看一下 `机器人文件夹\config\wordcloud_bg` 下的图片是否正常，如果不正常（大小0k，显示图片损坏，那就是由于cdn的问题导致图片在下载时失败，目前没有这方面的错误处理），如果正常，那我就不知道了

所以wordcloud依赖要装是吗，我机器人的依赖好像和这个依赖冲突
![image](https://user-images.githubusercontent.com/108536651/201002636-e3e18a28-6715-44e3-82c2-be900fbfa76c.png)
它会替换我机器人的依赖，然后就没法正常运行了

**Comment by yzyyz1387** [comment]
![image](https://user-images.githubusercontent.com/51691024/201002879-898354dd-1c52-4519-a44c-539bc2d8f139.png)
![image](https://user-images.githubusercontent.com/51691024/201002942-3dc22e7b-c052-41e8-b570-8bedb7482793.png)

**Comment by zuixiaoxiao** [comment]
> ![image](https://user-images.githubusercontent.com/51691024/201002879-898354dd-1c52-4519-a44c-539bc2d8f139.png) ![image](https://user-images.githubusercontent.com/51691024/201002942-3dc22e7b-c052-41e8-b570-8bedb7482793.png)

![image](https://user-images.githubusercontent.com/108536651/201008116-8f7d3edf-f769-4033-8dab-0a343d7ab2d4.png)
这样是下载好还是没下载好啊
