### ISSUE TITLE
插件导入报错

### ISSUE THREAD

**Issue by NanakoOfficial** [yzyyz1387/nonebot_plugin_admin#52]
from nonebot.adapters.onebot.exception import ActionFailed
ModuleNotFoundError: No module named 'nonebot.adapters.onebot.exception'

nonebot-adapter-onebot已经安装过，
是不是跟我py版本3.8+有关系（还有机会适配py3.8+么）

**Comment by yzyyz1387** [comment]
nonebot哪个版本的

**Comment by NanakoOfficial** [comment]
> nonebot哪个版本的

nonebot-adapter-onebot           2.1.3
nonebot2                         2.0.0b5

**Comment by yzyyz1387** [comment]
你有开发环境吗，
搜索所有的
 `from nonebot.adapters.onebot.exception import ActionFailed` 
改为
 `from nonebot.adapters.onebot.v11.exception import ActionFailed`
应该可以解决，我本地环境适配器是2.1.1， 很久没写代码了，刚才更新到2.1.3看了一下，这样应该没问题

**Comment by NanakoOfficial** [comment]
> 

已修改，现在还是报错
plugins\nonebot_plugin_admin\utils.py", line 38, in <module>
def At(data: str) -> Union[list[str], list[int], list]:
TypeError: 'type' object is not subscriptable

**Comment by yzyyz1387** [comment]
我这边环境没有问题，请问如上问题是否还存在
