### ISSUE TITLE
无法适配rc1

### ISSUE THREAD

**Issue by zuixiaoxiao** [yzyyz1387/nonebot_plugin_admin#53]
**描述 bug**
救命啊，插件出现了版本 问题

**如何复现**
1. 我通过nb方式安装并导入了插件
2. 在 启动时候 正常 情况下，出现了 无法加装 问题

**报错截图 （python的报错请截最下面）**
这里放截图，可使用任何截图工具截图，然后在这里按下 ** Ctrl + V **
![image](https://user-images.githubusercontent.com/108536651/197813674-ddd4a4c7-693c-4dbd-aeef-15564e6a01e8.png)
![image](https://user-images.githubusercontent.com/108536651/197813800-b3b9ef03-0ca6-428f-bff4-8fe86f856ab4.png)

**环境**
 - 操作系统  win10
 - Python 版本  3.9.13
 - Nonebot2 版本号 rc1
 - 在那里下载的本插件
  - github ( 说明分支 )main

**其他内容**
...

**Comment by yzyyz1387** [comment]
应该是版本不兼容，最近没时间做适配

**Comment by zuixiaoxiao** [comment]
> 应该是版本不兼容，最近没时间做适配

行吧，没找到其他好用的群管插件。只能等了，作者加油

**Comment by yzyyz1387** [comment]
虽然确实没适配rc1，但是我才发现，你截图的报错除了导入失败，其他没有一句是关于这个插件的
