### ISSUE TITLE
[BUG]无法使用任何群管功能，能启用的只有开关状态

### ISSUE THREAD

**Issue by Z735803792** [yzyyz1387/nonebot_plugin_admin#54]
**描述 bug**
无法使用任何群管功能，能启用的只有`开关状态`

**如何复现**
每次监测说一句话就弹一个报错，下面那个数字每次都不一样
**报错截图 （python的报错请截最下面）**
这里放截图，可使用任何截图工具截图，然后在这里按下 ** Ctrl + V **
![image](https://user-images.githubusercontent.com/70925546/200229771-bdb48e10-c8e8-45f3-a9b9-fdd78a5e252a.png)

**环境**
 - 操作系统 utunbu20.04
 - Python 版本 3.9.15
 - Nonebot2 版本号2.0.0b5
 - 在那里下载的本插件 nb商店
  - pypi (商店安装 或者 pip 安装（本质一样）)pip
  - github ( 说明分支 ) main

**其他内容**
...

**Comment by yzyyz1387** [comment]
请使用gh仓库版本而不是 pypi 版本

**Comment by Z735803792** [comment]
这次报错要怎么改
![image](https://user-images.githubusercontent.com/70925546/200231917-aa6154d0-a743-4d4f-a08c-19f41b6be900.png)

**Comment by yzyyz1387** [comment]
没适配新版，此类报错解决方法见 [No module named 'nonebot.adapters.onebot.exception'](https://github.com/yzyyz1387/cqsat/issues/2)
