### ISSUE TITLE
接收信息时报错

### ISSUE THREAD

**Issue by zuixiaoxiao** [yzyyz1387/nonebot_plugin_admin#56]
**描述 bug**
救命啊，插件出现了接收 信息报错 问题

**如何复现**
1. 我通过nb方式安装并导入了插件
2. 在 接收信息 时候 正常 情况下，出现了 报错 问题

**报错截图 （python的报错请截最下面）**
这里放截图，可使用任何截图工具截图，然后在这里按下 ** Ctrl + V **
![image](https://user-images.githubusercontent.com/108536651/202082339-de3ce87c-bef0-493f-8213-c507bdbbe194.png)
![image](https://user-images.githubusercontent.com/108536651/202082486-67862463-3395-455e-ac66-08d32cee690c.png)

**环境**
 - 操作系统  win10
 - Python 版本 3.9.13
 - Nonebot2 版本号 rc3
 - 在那里下载的本插件 nonebot商店
  - pypi (商店安装 或者 pip 安装（本质一样）)
  - github ( 说明分支 )  main

**其他内容**
...

**Comment by yzyyz1387** [comment]
这报错啥也看不出来![](https://api.isoyu.com/uploads/ARU/GIF_S/0171.gif)

**Comment by zuixiaoxiao** [comment]
> 这报错啥也看不出来![](https://camo.githubusercontent.com/2db7631357a1a72a27cf82ba20df80003a3de1aa18a9c6ca1712ebe37f165893/68747470733a2f2f6170692e69736f79752e636f6d2f75706c6f6164732f4152552f4749465f532f303137312e676966) [ ![68747470733a2f2f6170692e69736f79752e636f6d2f75706c6f6164732f4152552f4749465f532f303137312e676966](https://camo.githubusercontent.com/2db7631357a1a72a27cf82ba20df80003a3de1aa18a9c6ca1712ebe37f165893/68747470733a2f2f6170692e69736f79752e636f6d2f75706c6f6164732f4152552f4749465f532f303137312e676966) ](https://camo.githubusercontent.com/2db7631357a1a72a27cf82ba20df80003a3de1aa18a9c6ca1712ebe37f165893/68747470733a2f2f6170692e69736f79752e636f6d2f75706c6f6164732f4152552f4749465f532f303137312e676966) [ ](https://camo.githubusercontent.com/2db7631357a1a72a27cf82ba20df80003a3de1aa18a9c6ca1712ebe37f165893/68747470733a2f2f6170692e69736f79752e636f6d2f75706c6f6164732f4152552f4749465f532f303137312e676966)

虽然是不影响使用啦，但看起来很不舒服

**Comment by yzyyz1387** [comment]
我这边没出现这种情况，话说你nb rc3在那儿下的![](https://api.isoyu.com/uploads/ARU/GIF_S/4021.gif)

**Comment by zuixiaoxiao** [comment]
> 我这边没出现这种情况，话说你nb rc3在那儿下的![](https://camo.githubusercontent.com/2582f94962c79033ef7ec319f4d1fe43683221d113c88bd2c5d6c45192ccbd0a/68747470733a2f2f6170692e69736f79752e636f6d2f75706c6f6164732f4152552f4749465f532f343032312e676966) [ ![68747470733a2f2f6170692e69736f79752e636f6d2f75706c6f6164732f4152552f4749465f532f343032312e676966](https://camo.githubusercontent.com/2582f94962c79033ef7ec319f4d1fe43683221d113c88bd2c5d6c45192ccbd0a/68747470733a2f2f6170692e69736f79752e636f6d2f75706c6f6164732f4152552f4749465f532f343032312e676966) ](https://camo.githubusercontent.com/2582f94962c79033ef7ec319f4d1fe43683221d113c88bd2c5d6c45192ccbd0a/68747470733a2f2f6170692e69736f79752e636f6d2f75706c6f6164732f4152552f4749465f532f343032312e676966) [ ](https://camo.githubusercontent.com/2582f94962c79033ef7ec319f4d1fe43683221d113c88bd2c5d6c45192ccbd0a/68747470733a2f2f6170692e69736f79752e636f6d2f75706c6f6164732f4152552f4749465f532f343032312e676966)

不到机器人更新显示是这个
![image](https://user-images.githubusercontent.com/108536651/202207240-214d6b4f-51e5-4e00-87b5-6e96175b92db.png)

**Comment by zuixiaoxiao** [comment]
> > 我这边没出现这种情况，话说你nb rc3在那儿下的![](https://camo.githubusercontent.com/2582f94962c79033ef7ec319f4d1fe43683221d113c88bd2c5d6c45192ccbd0a/68747470733a2f2f6170692e69736f79752e636f6d2f75706c6f6164732f4152552f4749465f532f343032312e676966) [ ![68747470733a2f2f6170692e69736f79752e636f6d2f75706c6f6164732f4152552f4749465f532f343032312e676966](https://camo.githubusercontent.com/2582f94962c79033ef7ec319f4d1fe43683221d113c88bd2c5d6c45192ccbd0a/68747470733a2f2f6170692e69736f79752e636f6d2f75706c6f6164732f4152552f4749465f532f343032312e676966) ](https://camo.githubusercontent.com/2582f94962c79033ef7ec319f4d1fe43683221d113c88bd2c5d6c45192ccbd0a/68747470733a2f2f6170692e69736f79752e636f6d2f75706c6f6164732f4152552f4749465f532f343032312e676966) [ ](https://camo.githubusercontent.com/2582f94962c79033ef7ec319f4d1fe43683221d113c88bd2c5d6c45192ccbd0a/68747470733a2f2f6170692e69736f79752e636f6d2f75706c6f6164732f4152552f4749465f532f343032312e676966)
> 
> 不到机器人更新显示是这个 ![image](https://user-images.githubusercontent.com/108536651/202207240-214d6b4f-51e5-4e00-87b5-6e96175b92db.png)

重新安装也没用

**Comment by yzyyz1387** [comment]
找你借的报错确实看不出啥，要不试试删除插件的本地文件，就是`机器人项目/config`下的文件，截图中是关于 `word_analyze`这个文件的，你可以试着删除如下文件
![image](https://user-images.githubusercontent.com/51691024/202213393-91f7ae5d-7f03-45fc-a3e5-a3c65f3f3e4b.png)

（删除前可以留个备份

**Comment by zuixiaoxiao** [comment]
> 找你借的报错确实看不出啥，要不试试删除插件的本地文件，就是`机器人项目/config`下的文件，截图中是关于 `word_analyze`这个文件的，你可以试着删除如下文件 ![image](https://user-images.githubusercontent.com/51691024/202213393-91f7ae5d-7f03-45fc-a3e5-a3c65f3f3e4b.png)
> 
> （删除前可以留个备份

好像可以了，过会看看
