### ISSUE TITLE
自动禁言在关闭状态下还是会运行

### ISSUE THREAD

**Issue by zuixiaoxiao** [yzyyz1387/nonebot_plugin_admin#57]
**描述 bug**
救命啊，插件出现了自动禁言在关闭状态下还是会运行 问题

**如何复现**
1. 我通过 nb 方式安装并导入了插件
2. 在 触发违禁词 时候 关闭 情况下，出现了 禁言 问题

**报错截图 （python的报错请截最下面）**
这里放截图，可使用任何截图工具截图，然后在这里按下 ** Ctrl + V **
![image](https://user-images.githubusercontent.com/108536651/202913227-57ad53ea-63e7-4658-ad7b-26ce7cac77c4.png)
![image](https://user-images.githubusercontent.com/108536651/202913253-c3887b68-a801-45e3-acbe-c4e28b92b960.png)

**环境**
 - 操作系统 
 - Python 版本 3,9,13
 - Nonebot2 版本号  rc1
 - 在那里下载的本插件 nonebot商店
   - pypi (商店安装 或者 pip 安装（本质一样）)
   - github ( 说明分支 ) main

**其他内容**
...

**Comment by yzyyz1387** [comment]
什么时候安装的插件（判断插件版本）

**Comment by yzyyz1387** [comment]
违禁词这方面[@lakwsh](https://github.com/lakwsh)改的多，我没怎么关注，不过应该没问题，因为我刚试了下我的bot是正常的，  
你可以分别试试
- 用仓库的最新版
- 清空 `机器人/config/违禁词.txt` 和 `违禁词_简单.txt`，
- 再不行你就把插件的 `aotu_ban.py` 注掉不用

**Comment by zuixiaoxiao** [comment]
> 什么时候安装的插件（判断插件版本）

最新版，最近鼠标坏了所以一直没法回复，谢谢啦，虽然删了还是没办法
