### ISSUE TITLE
无法正常退出NoneBot？

### ISSUE THREAD

**Issue by lakwsh** [yzyyz1387/nonebot_plugin_admin#6]
这个插件好像会导致一个问题，在控制台按Ctrl+C会没有反应，但是NoneBot运作正常
系统：Window Server 2022

**Comment by lakwsh** [comment]
有个触发条件是调用了开关状态功能
怀疑是和Chromium有关，研究了一下跟pyppeteer有关系
根据 [https://github.com/miyakogi/pyppeteer/issues/105](https://github.com/miyakogi/pyppeteer/issues/105) 进行了相应修正工作

**Comment by yzyyz1387** [comment]
太忙了没及时回复，万分感谢你的贡献

**Comment by lakwsh** [comment]
嗯...好像还有个有点严重的Bug？也pull了

**Comment by yzyyz1387** [comment]
合了，感谢:)
