### ISSUE TITLE
[BUG]管理员+/-时，权限有问题

### ISSUE THREAD

**Issue by Reversedeer** [yzyyz1387/nonebot_plugin_admin#62]
通过指令：管理员+@user无法添加
看过其他的issues，可是似乎还是有问题

**环境**
 - 操作系统 ：centos7.9
 - Python 版本 3.9.10
 - Nonebot2 v2.0.0.b5
 - nb cli安装最新版插件
![image](https://user-images.githubusercontent.com/87823528/207211461-0cf5f717-1f94-412f-8778-2c6f0a86cb24.png)

**Comment by yzyyz1387** [comment]
重启协议端（go-cq）试试

**Comment by Reversedeer** [comment]
> 重新启动协议端（go-cq）测试

采取ipad协议登陆，仍然没有办法解决

**Comment by yzyyz1387** [comment]
有缓存，不是插件的问题

**Comment by yzyyz1387** [comment]
当我是群主，我把群转让给机器人后，执行此命令会出现同样的问题，当我重启go-cqhttp后得以解决，go-cqhttp的API有no_cache参数，不过我没看nb的onebot-adapter有没有相关参数，回头看看

**Comment by Reversedeer** [comment]
嗯嗯，是有存档没有更新，现在已经没问题了。不过wordcloud我手动安装后还需要进一步配置吗，发现还是无法检测到wordcloud
