### ISSUE TITLE
[功能建议]建议添加一个菜单

### ISSUE THREAD

**Issue by Reversedeer** [yzyyz1387/nonebot_plugin_admin#74]
暂且把这个功能命名为  : /指令
普通用户输入/ 指令可看到仅此身份下可执行的所有命令 (或者是出现所有的指令)
管理及以上 输入/指令 可以看到全部指令
或者可以提供一个菜单模板让SUPERUSER可以自定义菜单(推荐)
ps： 群友啥都不知道，整合那么多插件的机器人没菜单，但都知道这玩意会禁言qwq

**Comment by Reversedeer** [comment]
为了争第一......
![image](https://user-images.githubusercontent.com/87823528/209805963-38f33be3-4097-45ce-ad06-943e83e348c1.png)

**Comment by yzyyz1387** [comment]
在做了
[=>____________________|]  &emsp;0%

**Comment by Reversedeer** [comment]
我感觉在画大饼>=<

**Comment by yzyyz1387** [comment]
怎么会呢（确信

**Comment by Reversedeer** [comment]
是画大饼了(确信
