### ISSUE TITLE
[BUG] 长文本效验卡死进程 

### ISSUE THREAD

**Issue by babynanxi** [yzyyz1387/nonebot_plugin_admin#75]
接受到超长文本时卡死进程

**Comment by yzyyz1387** [comment]
多长，什么环境，什么版本，怎么卡死，如何复现，日志在哪里

**Comment by yzyyz1387** [comment]
![image](https://user-images.githubusercontent.com/51691024/210483630-58f438db-7421-4bac-9b24-3a5853c02a31.png)

**Comment by babynanxi** [comment]
![)M25$Y6K ~3%}%14 F(~MCM](https://user-images.githubusercontent.com/84330592/210502675-bd4233a7-15f8-4770-a0c5-89de09cf26ae.png)

![2KWA@ORG {7% EW092826EU](https://user-images.githubusercontent.com/84330592/210502733-ad4fd1eb-08a9-46fd-a319-b839298cab28.png)
无法退出进程 内存并没有占满

**Comment by yzyyz1387** [comment]
再麻烦说一下什么环境，什么版本，因为我这里没这个现象，无法复现
![image](https://user-images.githubusercontent.com/51691024/210535579-b0d6d26d-d06f-4773-bc4f-ec080898a31b.png)
