### ISSUE TITLE
[BUG] FileNotFoundError: [Errno 2] No such file or directory: 'config/广播排除群聊.json'

### ISSUE THREAD

**Issue by guohu7777** [yzyyz1387/nonebot_plugin_admin#76]
**描述 bug**
在没有config文件夹的情况下运行bot.py时没有自动创建文件夹而导致插件加载失败

**如何复现**
将config文件夹删除再次运行bot.py

**报错截图 （python的报错请截最下面）**
![image](https://user-images.githubusercontent.com/75009704/211046864-965493d2-7ee0-4c31-80d7-3a0c8d8324d9.png)
![image](https://user-images.githubusercontent.com/75009704/211046906-62114ff0-598f-49c9-8887-0e29c2d94bae.png)

**环境**
 - 操作系统 : windwos10 , ubuntu server 20.04.5 lts
 - Python 版本 : 3.10.9
 - Nonebot2 版本号 :  2.0.0rc2
 - 在那里下载的本插件
   - pypi (商店安装 或者 pip 安装（本质一样）)
   - github ( 说明分支 ) : main分支通过下载压缩包的方式进行解压后放在src/pugins/下

**其他内容**
无

**Comment by guohu7777** [comment]
解决办法是自己新建一个config文件夹

**Comment by yzyyz1387** [comment]
感谢对本插件的支持，并费心提出issue,该问题已解决，见：#80，在此回复发出的同时，插件更新还未发布在pypi，你可以使用仓库的代码更新插件，也可等待信release的发布，（仓库的release发布与pypi新版发布是同步的）

**Comment by Sydrr0** [comment]
> 解决办法是在bot.py目录下新建一个config文件夹

文件夹里面需要放什么呢
