### ISSUE TITLE
代码问题询问

### ISSUE THREAD

**Issue by Forgerly-OR-Henry** [yzyyz1387/nonebot_plugin_admin#77]
你好，我想问一下简易群管指令中【撤回@user[(可选，默认n=5)历史消息倍数n] (实际检查的历史数为 n*19)】怎么更改19这个基数，感觉19条消息有点多，谢谢。

**Comment by yzyyz1387** [comment]
@tom-snow 佬有时间解答一下吗![](https://api.isoyu.com/uploads/ARU/GIF_S/0540.gif)

**Comment by tom-snow** [comment]
19 是 go-cqhttp 默认的，参考：[go-cqhttp 文档](https://docs.go-cqhttp.org/api/#获取群消息历史记录)

如果你想改的话就得改一下 go-cqhttp 了

**Comment by Forgerly-OR-Henry** [comment]
非常感谢。
