### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Forgerly-OR-Henry** [yzyyz1387/nonebot_plugin_admin#78]
作者你好，感谢简易群管提供的便捷群管理，这里我想提一点建议，就是有的时候2000人的大QQ群20位管理员不一定都能24小时都能有人在线，有时候会有人传广告，讨论一些敏感话题，群友只能看着却无法撤回，导致群被风控，这里我希望功能中的分管不仅可以接收群处理消息，也可以操作机器人进行禁言，撤回，踢出，拉黑等功能，这样群管理人员就不止腾讯限制的20位了，如果分管的权限可以和机器人管理的操作权限相关联那就更好了，希望考虑一下，谢谢，支持投喂哦。

**Comment by yzyyz1387** [comment]
暂时为分管添加了部分权限，将来会日益完善，见：#79

**Comment by yzyyz1387** [comment]
暂时未发布至pypi，可查看文件差异拉取仓库文件进行体验，不过pypi也就这两天了，可能明天，（取决于我能否不摆烂而写点新东西

**Comment by Forgerly-OR-Henry** [comment]
已测试，目前效果良好，十分感谢作者采纳建议。
