### ISSUE TITLE
[BUG]使用群词云功能时，报错信息如下ValueError: Could not find a backend to open `config/wordcloud_bg/6.png`` with iomode `ri` 

### ISSUE THREAD

**Issue by Ayase-Naka-a** [yzyyz1387/nonebot_plugin_admin#81]
**描述 bug**
救命啊，使用群词云功能时，插件出现了报错，报错信息如下ValueError: Could not find a backend to open `config/wordcloud_bg/6.png`` with iomode `ri` 

**如何复现**
1. 我通过xxx 方式安装并导入了插件
2. 在 xx 时候 xx 情况下，出现了 xx 问题

**报错截图 （python的报错请截最下面）**
这里放截图，可使用任何截图工具截图，然后在这里按下 ** Ctrl + V **
![NP )44S5YUPD%$II``FZ24E](https://user-images.githubusercontent.com/117055433/215312316-0b3fae51-e999-47f0-9853-48bbcea226fe.png)

**环境**
 - 操作系统 ==centos
 - Python 版本 ==3.9.10
 - Nonebot2 版本号==rc.1
 - 在那里下载的本插件
   - pypi (商店安装 或者 pip 安装（本质一样）)
   - github ( 说明分支 )

**其他内容**
imageio插件版本是2.20.0，之前用的是2.25.0也有这个问题

**Comment by yzyyz1387** [comment]
应该是cdn的问题，那个我回头修复一下（一定会的），目前你可以将 https://wwvw.lanzouy.com/iboiq0m21fkb 的文件下载下来，里面是一些mask图片，把它们解压到 `机器人/config/wordcloud_bg/` 下,应该就可以用了

**Comment by yzyyz1387** [comment]
我猜是下载mask的时候由于cdn的问题没下好,我也没有写md5校验，所以你先试试

**Comment by Ayase-Naka-a** [comment]
已经尝试了，功能可以正常使用了，非常感谢

**Comment by Agnes4m** [comment]
# 插个眼

今天重新下插件，发现这个bug还没修，下载下来的图片是错误的

![image](https://user-images.githubusercontent.com/70925546/232980423-c24a4b15-dbb0-4384-acfa-62feeebe9930.png)

**Comment by Ayase-Naka-a** [comment]
你下载的文件解压有问题，试试用普通下载

![image](https://user-images.githubusercontent.com/117055433/232981748-4f1654f8-fd7d-4d15-bf56-103361b1fd22.png)

**Comment by Agnes4m** [comment]
手动下载确实是这个，但错误这个是插件自动下载的，和上面那位的报错一样，看上文说所以插个眼）
