### ISSUE TITLE
[BUG]防撤回功能开启后，功能不生效，日志报错如图

### ISSUE THREAD

**Issue by Ayase-Naka-a** [yzyyz1387/nonebot_plugin_admin#82]
**描述 bug**
插件开启防撤回后，防撤回功能不生效，日志报错

**如何复现**
1. 我通过pip方式安装并导入了插件
2. 在 开启防撤回功能后时候， 群里有人发消息后撤回情况下，防撤回功能不生效，查看bot日志有报错

**报错截图 （python的报错请截最下面）**
这里放截图，可使用任何截图工具截图，然后在这里按下 ** Ctrl + V **
![image](https://user-images.githubusercontent.com/117055433/215633648-ab8dbbbf-27b9-4f39-a21b-3a0a568880a6.png)

**环境**
 - 操作系统：centos
 - Python 版本：3.9.10
 - Nonebot2 版本号：2.0.0rc3
 - 在那里下载的本插件
   - pypi (商店安装 或者 pip 安装（本质一样）)：pip安装
   - github ( 说明分支 )

**其他内容**
...

**Comment by yzyyz1387** [comment]
抱歉，我暂时无法复现这个问题，请问：
1. 报错时撤回的消息是特定类型的还是所有撤回消息都报错
2. go-cqhttp的版本号
3. `pip show nonebot-plugin-admin 看看插件版本`

还有就是，如果方便，将以下代码替换到 `group_recall.py` 的最后一行之前，再撤回消息看一下输出什么
```
from nonebot import logger
logger.info(recalled_message)
logger.info(recall_notice)
```

**Comment by yzyyz1387** [comment]
前面三个问题我感觉不是特别重要，能添加后面的代码调试一下并截图就再好不过了

**Comment by Ayase-Naka-a** [comment]
pip版本信息：
![image](https://user-images.githubusercontent.com/117055433/215960288-c7124ea3-a1be-42ae-931e-5c85a9831306.png)

go-cq版本应该是[v1.0.0-rc3](https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-rc3)，具体怎么查看版本我不清楚，是2022年10月安装的bot，推测出是此版本


按照你说的，在group_recall.py 的最后一行之前加上日志信息的代码，
from nonebot import logger
logger.info(recalled_message)
logger.info(recall_notice)

截图如下所示：
bot在群里是管理员角色，用不是管理员也不是群主的账号分别发送了一条文字消息，一条图片消息，撤回后都有报错信息

![image](https://user-images.githubusercontent.com/117055433/215962554-43888c88-bcbc-4e32-a1be-a6fd2d4dbf89.png)

**Comment by Ayase-Naka-a** [comment]
这里是查看go-cq的日志信息
![FTX@J08XN{N I(W`WO~FM_6](https://user-images.githubusercontent.com/117055433/216001716-57351f48-abeb-4dfd-94ac-2db94c595f87.png)

**Comment by yzyyz1387** [comment]
嗯，我在找问题，很玄学，可能是我技术不精 

@lakwsh @tom-snow 怎么会事呢，救救
![image](https://user-images.githubusercontent.com/51691024/216002343-358855a5-e981-4447-8da2-3740a2d9bfb7.png)

代码见 https://github.com/yzyyz1387/nonebot_plugin_admin/blob/main/nonebot_plugin_admin/group_recall.py#L42-L44

但是用户这里的`recalled_message`
![image](https://user-images.githubusercontent.com/51691024/216002773-168485c3-bac4-4a64-8f01-cd1aaa7705c9.png)


怎么跟咱的不一样
![](https://user-images.githubusercontent.com/51691024/215996207-bfe46168-c7a1-45c8-bd67-ad5139ed50bf.png)

用户环境：
centos
nb: latest rc3
gocq: latest rc3
adapter-onebot:latest 2.2.1

**Comment by lakwsh** [comment]
> 嗯，我在找问题，很玄学，可能是我技术不精
> 
> @lakwsh @tom-snow 怎么会事呢，救救 ![image](https://user-images.githubusercontent.com/51691024/216002343-358855a5-e981-4447-8da2-3740a2d9bfb7.png)
> 
> 代码见 https://github.com/yzyyz1387/nonebot_plugin_admin/blob/main/nonebot_plugin_admin/group_recall.py#L42-L44
> 
> 但是用户这里的`recalled_message` ![image](https://user-images.githubusercontent.com/51691024/216002773-168485c3-bac4-4a64-8f01-cd1aaa7705c9.png)
> 
> 怎么跟咱的不一样 ![](https://user-images.githubusercontent.com/51691024/215996207-bfe46168-c7a1-45c8-bd67-ad5139ed50bf.png)
> 
> 用户环境： centos nb: latest rc3 gocq: latest rc3 adapter-onebot:latest 2.2.1

用is_text()判断一下再处理咯，https://v2.nonebot.dev/docs/tutorial/process-message#%E8%8E%B7%E5%8F%96%E6%B6%88%E6%81%AF%E7%BA%AF%E6%96%87%E6%9C%AC

**Comment by yzyyz1387** [comment]
> 用is_text()判断一下再处理咯，https://v2.nonebot.dev/docs/tutorial/process-message#%E8%8E%B7%E5%8F%96%E6%B6%88%E6%81%AF%E7%BA%AF%E6%96%87%E6%9C%AC

复现不了，没法修(哭

**Comment by Ayase-Naka-a** [comment]
await bot.send_group_msg(group_id=group_id, message=recall_notice + recalled_message['message'])

不知道要怎么使用，是要判断上面的message吗
尝试在group_recall最后面加上下面这句

MessageSegment.text(message).is_text() == True

bot运行日志里没有输出

**Comment by tom-snow** [comment]
试试清理环境重新搭建机器人看看能不能解决。或者留下联系方式抽空在你的环境看看是啥情况

**Comment by Ayase-Naka-a** [comment]
好的，麻烦请加一下我的qq：499313487，验证问题答案：Ω，我把云服务器的ip及密码给你，帮忙远程调试一下

**Comment by tom-snow** [comment]
Fixed: [here](https://github.com/yzyyz1387/nonebot_plugin_admin/commit/710091e9d1ea2321945ca5899d64a9c56c33dec1)

**Comment by lakwsh** [comment]
> Fixed: [here](https://github.com/yzyyz1387/nonebot_plugin_admin/commit/710091e9d1ea2321945ca5899d64a9c56c33dec1)

![_GOC~H%QGXR@@PNBG19A% Y](https://user-images.githubusercontent.com/13025769/220877197-4149d1c5-79f0-4f3a-9d75-d2fb77cf1c7c.gif)

**Comment by yzyyz1387** [comment]
> Fixed: [here](https://github.com/yzyyz1387/nonebot_plugin_admin/commit/710091e9d1ea2321945ca5899d64a9c56c33dec1)

![-250c677c8d9b8379.jpg](https://user-images.githubusercontent.com/51691024/220879988-8ea3e96c-11e5-4d2c-a074-a7078c8b556c.jpg)
