### ISSUE TITLE
[建议]新增简化功能版本

### ISSUE THREAD

**Issue by Umamusume-Agnes-Digital** [yzyyz1387/nonebot_plugin_admin#85]
nb端显示太多了，感觉越来越复杂了。我希望有一个只有如下功能的版本：
1、（管理）禁言、踢、改群名片、群申请、撤回、设精
2、（群主）设置管理员、设置头衔
如果您同意的话，我可以fork做一个简化版本，因为现在真的emmm不简易啊

**Comment by yzyyz1387** [comment]
设...设什么？![](https://api.isoyu.com/uploads/ARU/GIF_S/5120.gif)

**Comment by yzyyz1387** [comment]
可以的，你也可以做出来上架到商店，不过我看商店好像有一个类似的。我考研的事还没结束，所以没空管这些东西
